SERVER_BUFFER_SIZE = 128 * 1024
SERVER_PORT = 3571
SERVER_HOST = '0.0.0.0'
SERVER_MAX_CONNECTIONS = 10
SERVER_MUSIC_DIRECTORY = "/home/michaleq/Music/albums"
SERVER_INDEX_PATH = 'index.json'
SERVER_FILE_ID_LENGTH = 5
SERVER_SEARCH_RESULT_LIMIT = 8